# Я художник, я так вижу, визуализация данных в питоне

# I. Numpy

### Импортируйте NumPy

In [35]:
# ВАШ КОД ЗДЕСЬ
import numpy as np

### Создайте одномерный массив размера 10, заполненный нулями и пятым элемент равным 1. Трансформируйте в двумерный массив.

In [10]:
# ВАШ КОД ЗДЕСЬ
arr = np.zeros(10)
arr[4] = 1
arr.shape = (2, 5)
print(arr)

[[0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


### Создайте одномерный массив со значениями от 10 до 49 и разверните его (первый элемент становится последним). Найдите в нем все четные элементы.

In [17]:
# ВАШ КОД ЗДЕСЬ
arr = np.arange(10, 50)
reverse_arr = np.flip(arr)
mode_2 =0 == (reverse_arr % 2)
reverse_arr_mode_2 = reverse_arr[mode_2]
print(reverse_arr)
print(mode_2)
print(reverse_arr_mode_2)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
[False  True False  True False  True False  True False  True False  True
 False  True False  True False  True False  True False  True False  True
 False  True False  True False  True False  True False  True False  True
 False  True False  True]
[48 46 44 42 40 38 36 34 32 30 28 26 24 22 20 18 16 14 12 10]


### Создайте двумерный массив 3x3 со значениями от 0 до 8

In [20]:
# ВАШ КОД ЗДЕСЬ
arr = np.arange(0, 9).reshape(3, 3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Создайте массив 4x3x2 со случайными значениями. Найти его минимум и максимум.

In [34]:
# ВАШ КОД ЗДЕСЬ
arr = np.random.rand(4, 3, 2)
min_arr = arr.min()
max_arr = arr.max()
print(arr)
print(f' Минимальное значение в массиве:  {min_arr}, ', 
      f' максимальное значение в массиве: {max_arr}')

[[[0.35646549 0.64901121]
  [0.46787737 0.56671094]
  [0.32162665 0.37541834]]

 [[0.36240984 0.41120487]
  [0.12528429 0.02409135]
  [0.34147625 0.83168216]]

 [[0.54179598 0.69340193]
  [0.75832812 0.48068125]
  [0.70725344 0.81710021]]

 [[0.72825502 0.82090473]
  [0.59352503 0.87874971]
  [0.18073177 0.047549  ]]]
 Минимальное значение в массиве:  0.024091353307196695,   максимальное значение в массиве: 0.8787497083980739


### Создайте два двумерных массива размерами 6x4 и 4x3 и произведите их матричное умножение. 

In [40]:
# ВАШ КОД ЗДЕСЬ
arr_1 = np.random.rand(6, 4)
arr_2 = np.random.rand(4, 3)
display(arr_1, arr_2)
dot_arrs = np.dot(arr_1, arr_2)
print(dot_arrs)

array([[0.38223838, 0.13163786, 0.26673404, 0.01304885],
       [0.11954051, 0.05558236, 0.37004741, 0.58354858],
       [0.08268804, 0.11913996, 0.65708288, 0.36368583],
       [0.43819712, 0.3326963 , 0.58238165, 0.00155352],
       [0.58855246, 0.70543465, 0.90009986, 0.52406887],
       [0.39919843, 0.81309414, 0.5977208 , 0.0131085 ]])

array([[0.94151222, 0.52799948, 0.50990333],
       [0.01539816, 0.03499469, 0.43245709],
       [0.1055354 , 0.4293797 , 0.25685016],
       [0.27698854, 0.02117989, 0.50238744]])

[[0.39367335 0.32123485 0.32689861]
 [0.31409409 0.23631275 0.47320531]
 [0.24976864 0.33766938 0.44516886]
 [0.47958304 0.49310622 0.51768033]
 [0.80514519 0.73302619 1.09965149]
 [0.45508196 0.49615736 0.71529117]]


### Создайте случайный двумерный массив 7x7, найти у него среднее и стандартное оклонение. Нормализуйте этот массив.

In [ ]:
# ВАШ КОД ЗДЕСЬ

# II. Pandas

### Импортируйте: pandas, matplotlib, seaborn

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Загрузите датасет Tips из набора датасетов seaborn

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Посмотрите на первые 5 строчек

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Узнайте сколько всего строчек и колонок в данных

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Проверьте есть ли пропуски в данных

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Посмотрите на распределение числовых признаков

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Найдите максимальное значение 'total_bill'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Найдите количество курящих людей

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Узнайте какой средний 'total_bill' в зависимости от 'day'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Отберите строчки с 'total_bill' больше медианы и узнайте какой средний 'tip' в зависимости от 'sex'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Преобразуйте признак 'smoker' в бинарный (0-No, 1-Yes)

In [ ]:
# ВАШ КОД ЗДЕСЬ

# III. Visualization

### Постройте гистограмму распределения признака 'total_bill'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Постройте scatterplot, представляющий взаимосвязь между признаками 'total_bill' и 'tip'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Постройте pairplot

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Постройте график взаимосвязи между признаками 'total_bill' и 'day'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Постройте две гистограммы распределения признака 'tip' в зависимости от категорий 'time'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Постройте два графика scatterplot, представляющих взаимосвязь между признаками 'total_bill' и 'tip' один для Male, другой для Female и раскрасьте точки в зависимоти от признака 'smoker'

In [ ]:
# ВАШ КОД ЗДЕСЬ

## Сделайте выводы по анализу датасета и построенным графикам. По желанию можете продолжить анализ данных и также отразить это в выводах.

In [ ]:
# ВАШ КОД ЗДЕСЬ