# Я художник, я так вижу, визуализация данных в питоне

# I. Numpy

### Импортируйте NumPy

In [41]:
# ВАШ КОД ЗДЕСЬ
import numpy as np

### Создайте одномерный массив размера 10, заполненный нулями и пятым элемент равным 1. Трансформируйте в двумерный массив.

In [10]:
# ВАШ КОД ЗДЕСЬ
arr = np.zeros(10)
arr[4] = 1
arr.shape = (2, 5)
print(arr)

[[0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


### Создайте одномерный массив со значениями от 10 до 49 и разверните его (первый элемент становится последним). Найдите в нем все четные элементы.

In [17]:
# ВАШ КОД ЗДЕСЬ
arr = np.arange(10, 50)
reverse_arr = np.flip(arr)
mode_2 =0 == (reverse_arr % 2)
reverse_arr_mode_2 = reverse_arr[mode_2]
print(reverse_arr)
print(mode_2)
print(reverse_arr_mode_2)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
[False  True False  True False  True False  True False  True False  True
 False  True False  True False  True False  True False  True False  True
 False  True False  True False  True False  True False  True False  True
 False  True False  True]
[48 46 44 42 40 38 36 34 32 30 28 26 24 22 20 18 16 14 12 10]


### Создайте двумерный массив 3x3 со значениями от 0 до 8

In [20]:
# ВАШ КОД ЗДЕСЬ
arr = np.arange(0, 9).reshape(3, 3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Создайте массив 4x3x2 со случайными значениями. Найти его минимум и максимум.

In [34]:
# ВАШ КОД ЗДЕСЬ
arr = np.random.rand(4, 3, 2)
min_arr = arr.min()
max_arr = arr.max()
print(arr)
print(f' Минимальное значение в массиве:  {min_arr}, ', 
      f' максимальное значение в массиве: {max_arr}')

[[[0.35646549 0.64901121]
  [0.46787737 0.56671094]
  [0.32162665 0.37541834]]

 [[0.36240984 0.41120487]
  [0.12528429 0.02409135]
  [0.34147625 0.83168216]]

 [[0.54179598 0.69340193]
  [0.75832812 0.48068125]
  [0.70725344 0.81710021]]

 [[0.72825502 0.82090473]
  [0.59352503 0.87874971]
  [0.18073177 0.047549  ]]]
 Минимальное значение в массиве:  0.024091353307196695,   максимальное значение в массиве: 0.8787497083980739


### Создайте два двумерных массива размерами 6x4 и 4x3 и произведите их матричное умножение. 

In [40]:
# ВАШ КОД ЗДЕСЬ
arr_1 = np.random.rand(6, 4)
arr_2 = np.random.rand(4, 3)
display(arr_1, arr_2)
dot_arrs = np.dot(arr_1, arr_2)
print(dot_arrs)

array([[0.38223838, 0.13163786, 0.26673404, 0.01304885],
       [0.11954051, 0.05558236, 0.37004741, 0.58354858],
       [0.08268804, 0.11913996, 0.65708288, 0.36368583],
       [0.43819712, 0.3326963 , 0.58238165, 0.00155352],
       [0.58855246, 0.70543465, 0.90009986, 0.52406887],
       [0.39919843, 0.81309414, 0.5977208 , 0.0131085 ]])

array([[0.94151222, 0.52799948, 0.50990333],
       [0.01539816, 0.03499469, 0.43245709],
       [0.1055354 , 0.4293797 , 0.25685016],
       [0.27698854, 0.02117989, 0.50238744]])

[[0.39367335 0.32123485 0.32689861]
 [0.31409409 0.23631275 0.47320531]
 [0.24976864 0.33766938 0.44516886]
 [0.47958304 0.49310622 0.51768033]
 [0.80514519 0.73302619 1.09965149]
 [0.45508196 0.49615736 0.71529117]]


### Создайте случайный двумерный массив 7x7, найти у него среднее и стандартное оклонение. Нормализуйте этот массив.

In [70]:
# ВАШ КОД ЗДЕСЬ
np.random.seed(22)
arr = np.random.randint(1, 100, size=(7, 7))
arr_mean = np.mean(arr)
arr_std = np.std(arr)
#normalize_arr = (arr - arr.mean(axis=0)) / arr.std(axis=0)
normalize_arr = (arr - arr_mean) / arr_std
print(arr)
print(f' Среднее значение в массиве: {arr_mean}')
print(f' Стандартное отклонение в массиве: {arr_std}')
print(normalize_arr)

[[ 5 45 65 85  9 96 94]
 [19 15 46 89 94 40 35]
 [42  9 41  6 28 85 35]
 [30 83 82 39 20 20 67]
 [92  8 28 24 24 12 95]
 [14 53 76 48  2 48 88]
 [84 59 61 49 94 60 94]]
 Среднее значение в массиве: 49.734693877551024
 Стандартное отклонение в массиве: 30.483702912763665
[[-1.4674954  -0.15531886  0.50076942  1.15685769 -1.33627775  1.51770624
   1.45209741]
 [-1.00823361 -1.13945127 -0.12251444  1.28807534  1.45209741 -0.31934092
  -0.48336299]
 [-0.2537321  -1.33627775 -0.28653651 -1.43469099 -0.71299389  1.15685769
  -0.48336299]
 [-0.64738506  1.09124886  1.05844445 -0.35214534 -0.9754292  -0.9754292
   0.56637824]
 [ 1.38648859 -1.36908216 -0.71299389 -0.84421154 -0.84421154 -1.23786451
   1.48490183]
 [-1.17225568  0.10711645  0.86161797 -0.05690562 -1.56590864 -0.05690562
   1.25527093]
 [ 1.12405328  0.30394293  0.36955176 -0.0241012   1.45209741  0.33674735
   1.45209741]]


# II. Pandas

### Импортируйте: pandas, matplotlib, seaborn

In [86]:
# ВАШ КОД ЗДЕСЬ
import pandas as pd
import matplotlib as mpl
import seaborn as sns

### Загрузите датасет Tips из набора датасетов seaborn

In [111]:
# ВАШ КОД ЗДЕСЬ
tips = sns.load_dataset("tips")

### Посмотрите на первые 5 строчек

In [88]:
# ВАШ КОД ЗДЕСЬ
print(tips.head())

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4


### Узнайте сколько всего строчек и колонок в данных

In [89]:
# ВАШ КОД ЗДЕСЬ
print(tips.shape)

(244, 7)


### Проверьте есть ли пропуски в данных

In [90]:
# ВАШ КОД ЗДЕСЬ
print(tips.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64   
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB
None


### Посмотрите на распределение числовых признаков

In [91]:
# ВАШ КОД ЗДЕСЬ
print(tips.describe())

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000


### Найдите максимальное значение 'total_bill'

In [94]:
# ВАШ КОД ЗДЕСЬ
max_ttl_bill = tips['total_bill'].max()
print(max_ttl_bill)

50.81


### Найдите количество курящих людей

In [116]:
# ВАШ КОД ЗДЕСЬ
cnt_no_smoke = tips[tips.smoker == 'Yes'].shape[0]
print(cnt_no_smoke)


93


### Узнайте какой средний 'total_bill' в зависимости от 'day'

In [118]:
# ВАШ КОД ЗДЕСЬ
mean_ttl_bill_by_day = tips.groupby(['day'])['total_bill'].mean()
print(mean_ttl_bill_by_day)

day
Thur    17.682742
Fri     17.151579
Sat     20.441379
Sun     21.410000
Name: total_bill, dtype: float64


C:\Users\Nastya\AppData\Local\Temp\ipykernel_4668\2930030325.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  mean_ttl_bill_by_day = tips.groupby(['day'])['total_bill'].mean()


### Отберите строчки с 'total_bill' больше медианы и узнайте какой средний 'tip' в зависимости от 'sex'

In [126]:
# ВАШ КОД ЗДЕСЬ
mean_tip_by_sex = tips[tips.total_bill > tips.total_bill.median()].groupby(['sex'])['tip'].mean()
print(mean_tip_by_sex)

sex
Male      3.756404
Female    3.663939
Name: tip, dtype: float64


C:\Users\Nastya\AppData\Local\Temp\ipykernel_4668\1100548467.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  mean_tip_by_sex = tips[tips.total_bill > tips.total_bill.median()].groupby(['sex'])['tip'].mean()


### Преобразуйте признак 'smoker' в бинарный (0-No, 1-Yes)

In [ ]:
# ВАШ КОД ЗДЕСЬ

# III. Visualization

### Постройте гистограмму распределения признака 'total_bill'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Постройте scatterplot, представляющий взаимосвязь между признаками 'total_bill' и 'tip'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Постройте pairplot

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Постройте график взаимосвязи между признаками 'total_bill' и 'day'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Постройте две гистограммы распределения признака 'tip' в зависимости от категорий 'time'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Постройте два графика scatterplot, представляющих взаимосвязь между признаками 'total_bill' и 'tip' один для Male, другой для Female и раскрасьте точки в зависимоти от признака 'smoker'

In [ ]:
# ВАШ КОД ЗДЕСЬ

## Сделайте выводы по анализу датасета и построенным графикам. По желанию можете продолжить анализ данных и также отразить это в выводах.

In [ ]:
# ВАШ КОД ЗДЕСЬ